name: CI
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - master
      - develop
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Start Network
        run:
          ./startNetwork.sh
      - name: Check Network
        run: kubectl get all -n hlf-production-network
      - name: Delete Network
        run:
          ./deleteNetwork.sh
      - name: Check Network
        run: kubectl get all -n hlf-production-network
      - name: Start Network again
        run:
          ./startNetwork.sh
      - name: Check Network
        run: kubectl get all -n hlf-production-network
      - name: Install Chaincode
        run:
          ./installChaincode.sh
      - name: Test Installed Chaincode
        run:
          ./testInstalledChaincode.sh
